[2023-01-06T12:29:08.095+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.upload_get_yfinance_data_to_s3 scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:29:08.107+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.upload_get_yfinance_data_to_s3 scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:29:08.107+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:29:08.107+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-06T12:29:08.107+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:29:08.122+0000] {taskinstance.py:1389} INFO - Executing <Task(LocalFilesystemToS3Operator): upload_get_yfinance_data_to_s3> on 2023-01-06 00:00:00+00:00
[2023-01-06T12:29:08.127+0000] {standard_task_runner.py:52} INFO - Started process 84 to run task
[2023-01-06T12:29:08.130+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_import_data_from_apis', 'upload_get_yfinance_data_to_s3', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '3819', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/import_data_from_apis.py', '--cfg-path', '/tmp/tmpp773k7u2', '--error-file', '/tmp/tmp55tcm7ry']
[2023-01-06T12:29:08.130+0000] {standard_task_runner.py:80} INFO - Job 3819: Subtask upload_get_yfinance_data_to_s3
[2023-01-06T12:29:08.145+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:538: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-06T12:29:08.193+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_import_data_from_apis.upload_get_yfinance_data_to_s3 scheduled__2023-01-06T00:00:00+00:00 [running]> on host 370ed6868bc3
[2023-01-06T12:29:08.265+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_import_data_from_apis
AIRFLOW_CTX_TASK_ID=upload_get_yfinance_data_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-06T12:29:08.278+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T12:29:08.279+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-06T12:29:09.804+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=atn_import_data_from_apis, task_id=upload_get_yfinance_data_to_s3, execution_date=20230106T000000, start_date=20230106T122908, end_date=20230106T122909
[2023-01-06T12:29:09.836+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-06T12:29:09.909+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-06T12:33:12.422+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.upload_get_yfinance_data_to_s3 scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:33:12.435+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_import_data_from_apis.upload_get_yfinance_data_to_s3 scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2023-01-06T12:33:12.435+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:33:12.435+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-06T12:33:12.435+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T12:33:12.451+0000] {taskinstance.py:1389} INFO - Executing <Task(LocalFilesystemToS3Operator): upload_get_yfinance_data_to_s3> on 2023-01-06 00:00:00+00:00
[2023-01-06T12:33:12.456+0000] {standard_task_runner.py:52} INFO - Started process 126 to run task
[2023-01-06T12:33:12.474+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_import_data_from_apis', 'upload_get_yfinance_data_to_s3', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '3832', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/import_data_from_apis.py', '--cfg-path', '/tmp/tmpxopovlgi', '--error-file', '/tmp/tmpqum_cgrb']
[2023-01-06T12:33:12.476+0000] {standard_task_runner.py:80} INFO - Job 3832: Subtask upload_get_yfinance_data_to_s3
[2023-01-06T12:33:12.501+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:538: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-06T12:33:12.555+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_import_data_from_apis.upload_get_yfinance_data_to_s3 scheduled__2023-01-06T00:00:00+00:00 [running]> on host 370ed6868bc3
[2023-01-06T12:33:12.631+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_import_data_from_apis
AIRFLOW_CTX_TASK_ID=upload_get_yfinance_data_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2023-01-06T12:33:12.643+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T12:33:12.643+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-06T12:33:14.243+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=atn_import_data_from_apis, task_id=upload_get_yfinance_data_to_s3, execution_date=20230106T000000, start_date=20230106T123312, end_date=20230106T123314
[2023-01-06T12:33:14.285+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-06T12:33:14.369+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
