[2023-01-06T13:22:45.263+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_update_datalake.create_second_emr manual__2023-01-06T13:21:32.663212+00:00 [queued]>
[2023-01-06T13:22:45.275+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: atn_update_datalake.create_second_emr manual__2023-01-06T13:21:32.663212+00:00 [queued]>
[2023-01-06T13:22:45.275+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T13:22:45.275+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 3
[2023-01-06T13:22:45.276+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-01-06T13:22:45.290+0000] {taskinstance.py:1389} INFO - Executing <Task(EmrCreateJobFlowOperator): create_second_emr> on 2023-01-06 13:21:32.663212+00:00
[2023-01-06T13:22:45.295+0000] {standard_task_runner.py:52} INFO - Started process 373 to run task
[2023-01-06T13:22:45.298+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'atn_update_datalake', 'create_second_emr', 'manual__2023-01-06T13:21:32.663212+00:00', '--job-id', '3916', '--raw', '--subdir', 'DAGS_FOLDER/market_data_analytics/my_dags/datalake_update.py', '--cfg-path', '/tmp/tmpdjbecx4n', '--error-file', '/tmp/tmp2dv6xodk']
[2023-01-06T13:22:45.299+0000] {standard_task_runner.py:80} INFO - Job 3916: Subtask create_second_emr
[2023-01-06T13:22:45.362+0000] {task_command.py:371} INFO - Running <TaskInstance: atn_update_datalake.create_second_emr manual__2023-01-06T13:21:32.663212+00:00 [running]> on host 370ed6868bc3
[2023-01-06T13:22:45.437+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=atn
AIRFLOW_CTX_DAG_ID=atn_update_datalake
AIRFLOW_CTX_TASK_ID=create_second_emr
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T13:21:32.663212+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-06T13:21:32.663212+00:00
[2023-01-06T13:22:45.438+0000] {emr.py:297} INFO - Creating JobFlow using aws-conn-id: aws_credentials, emr-conn-id: aws_credentials
[2023-01-06T13:22:45.448+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T13:22:45.454+0000] {base.py:68} INFO - Using connection ID 'aws_credentials' for task execution.
[2023-01-06T13:22:45.455+0000] {connection_wrapper.py:210} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2023-01-06T13:22:46.678+0000] {emr.py:311} INFO - JobFlow with id j-3G7PO8Y3OE3BT created
[2023-01-06T13:22:46.748+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=atn_update_datalake, task_id=create_second_emr, execution_date=20230106T132132, start_date=20230106T132245, end_date=20230106T132246
[2023-01-06T13:22:46.805+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-06T13:22:46.887+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
